# Generated by Django 5.1 on 2024-09-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_title', models.CharField(max_length=150)),
                ('dynamic_desc', models.TextField()),
                ('dynamic_img_link', models.CharField(max_length=150)),
                ('dynamic_read_link', models.CharField(max_length=150)),
            ],
        ),
    ]
