# Generated by Django 5.1 on 2024-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='dynamic_imgg',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media'),
        ),
    ]
